name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm i npm@latest
      - run: npm i
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: mkdir -p docs
      - name: Check for collection file
        run: ls -la # this will list all files in current directory, to check for collection file.
      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export docs/index.html || true
      - name: Check for HTML report
        run: ls -la docs # this will list all files in the docs directory, to check for index.html.
      - name: Print out HTML report
        run: cat docs/index.html # this will print out the contents of index.html.
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: docs
